apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: argocd-additional-access
rules:
- apiGroups: [""]
  resources: ["services","serviceaccounts"]
  verbs:
  - "*"
- apiGroups:
  - route.openshift.io
  resources:
  - routes
  verbs:
  - "*"
- apiGroups: 
  - "apps"
  resources: 
  - "deployments"
  verbs:
  - "*"
- apiGroups:
  - "external-secrets.io"
  resources:
    - "secretstores"
    - "externalsecrets"
  verbs:
  - "*"
