# apiVersion: policy.open-cluster-management.io/v1
# kind: PolicyGenerator
# metadata:
#   name: rhsso-policy-generator

# policyDefaults:
#   namespace: policies
#   remediationAction: enforce
#   complianceType: musthave
#   severity: medium
#   placement:
#     clusterSelectors:
#       matchLabels:
#           local-cluster: "true"


# policies:
#   - name: install-rhsso
#     manifests:
#       - path: raw-policies/install-rhsso-subscription.yaml

#   - name: configure-rhsso
#     manifests:
#       - path: raw-policies/configure-keycloak-instance.yaml
