apiVersion: k8s.keycloak.org/v2alpha1
kind: Keycloak
metadata:
  name: rhsso
  labels:
    app: sso
  namespace: rhsso
spec:
  tracing:
    enabled: false
  update:
    strategy: RecreateOnImageChange
  instances: 1
  http:
    httpEnabled: true
  hostname:
    strict: false
  ingress:
    enabled: true  