apiVersion: keycloak.org/v1alpha1
kind: Keycloak
metadata:
  name: rhsso
  namespace: keycloak
spec: {}

---
apiVersion: keycloak.org/v1alpha1
kind: KeycloakRealm
metadata:
  name: myrealm
  namespace: keycloak
spec:
  instanceSelector:
    matchLabels:
      app: rhsso
