apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: aws-cluster-secretstore
spec:
  provider:
    aws:
      auth:
        secretRef:
          accessKeyIDSecretRef:
            key: access-key
            name: aws-secret
            namespace: external-secrets
          secretAccessKeySecretRef:
            key: aws-secret-access-key
            name: aws-secret
            namespace: external-secrets
      region: ap-southeast-2
      service: SecretsManager