apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: petclinic-secret
  namespace: petclinic
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: aws-cluster-secretstore
    kind: ClusterSecretStore
  target:
    name: demo-db
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: petclinic-secret