apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: aws-secrets
  namespace: petclinic
spec:
  provider:
    aws:
      service: SecretsManager
      region: ap-southeast-2  # Change to your region
      auth:
        jwt:
          serviceAccountRef:
            name: eso-sa