apiVersion: policy.open-cluster-management.io/v1
kind: PolicyGenerator
metadata:
  name: acs-policy-generator

policyDefaults:
  namespace: policies
  remediationAction: enforce
  complianceType: musthave
  severity: medium
  


policies:
  - name: install-acs-hub
    manifests:
      - path: hub-cluster/acs-central-and-securedcluster.yaml
    placement:
    clusterSelectors:
      matchLabels:
          local-cluster: "true"  

  - name: install-acs-managed
    manifests:
      - path: raw-policies/configure-keycloak-instance.yaml
    placement:
    clusterSelectors:
    matchExpressions:
      - key: local-cluster
        operator: NotIn
        values: ["true"]
